2018-09-18T17:38:46|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\Users\user\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\user\eclipse-workspace\Shutter\shutter_hw.py", line 24, in connect
    self.shutter_closed.hardware_set_func = self.shutter.change_shutter
AttributeError: 'bool' object has no attribute 'hardware_set_func'

